# Generated by Django 5.2.3 on 2025-06-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Кімната', 'verbose_name_plural': 'Кімнати'},
        ),
        migrations.AlterModelOptions(
            name='typeroom',
            options={'verbose_name': 'Тип кімнати', 'verbose_name_plural': 'Тип кімнат'},
        ),
    ]
